//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Measure.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Recurso {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recurso() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Measure.Recursos.Recurso", typeof(Recurso).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acción.
        /// </summary>
        public static string Accion {
            get {
                return ResourceManager.GetString("Accion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anterior.
        /// </summary>
        public static string Antes {
            get {
                return ResourceManager.GetString("Antes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellidos.
        /// </summary>
        public static string Apellidos {
            get {
                return ResourceManager.GetString("Apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo entrada una linea.
        /// </summary>
        public static string Ca_Entrada {
            get {
                return ResourceManager.GetString("Ca_Entrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo entrada una linea con texto antes y/o despues.
        /// </summary>
        public static string Ca_Entrada_Descripcion {
            get {
                return ResourceManager.GetString("Ca_Entrada_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo entrada multilinea.
        /// </summary>
        public static string Ca_Entrada_Multiple {
            get {
                return ResourceManager.GetString("Ca_Entrada_Multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rango.
        /// </summary>
        public static string Ca_Rango {
            get {
                return ResourceManager.GetString("Ca_Rango", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo de texto multiple.
        /// </summary>
        public static string Ca_Texto_Multiple {
            get {
                return ResourceManager.GetString("Ca_Texto_Multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccion.
        /// </summary>
        public static string Cc_Desplegable {
            get {
                return ResourceManager.GetString("Cc_Desplegable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unica respuesta.
        /// </summary>
        public static string Cc_Enlistada {
            get {
                return ResourceManager.GetString("Cc_Enlistada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unica respuesta anidada.
        /// </summary>
        public static string Cc_Enlistada_Anidada {
            get {
                return ResourceManager.GetString("Cc_Enlistada_Anidada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unica respuesta mas otro.
        /// </summary>
        public static string Cc_Enlistada_Otro {
            get {
                return ResourceManager.GetString("Cc_Enlistada_Otro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respuesta multiple.
        /// </summary>
        public static string Cc_Opcion_Multiple {
            get {
                return ResourceManager.GetString("Cc_Opcion_Multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respuesta multiple mas otro.
        /// </summary>
        public static string Cc_Opcion_Multiple_Otro {
            get {
                return ResourceManager.GetString("Cc_Opcion_Multiple_Otro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar.
        /// </summary>
        public static string Confirmar {
            get {
                return ResourceManager.GetString("Confirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar.
        /// </summary>
        public static string Continuar {
            get {
                return ResourceManager.GetString("Continuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preguntas abiertas.
        /// </summary>
        public static string ControlAbierto {
            get {
                return ResourceManager.GetString("ControlAbierto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregunta SI / NO.
        /// </summary>
        public static string ControlBooleano {
            get {
                return ResourceManager.GetString("ControlBooleano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preguntas Cerradas.
        /// </summary>
        public static string ControlCerrado {
            get {
                return ResourceManager.GetString("ControlCerrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matriz de Seleccion.
        /// </summary>
        public static string ControlMatriz {
            get {
                return ResourceManager.GetString("ControlMatriz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas los controles.
        /// </summary>
        public static string ControlTodo {
            get {
                return ResourceManager.GetString("ControlTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;es&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;Correo&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;font-family: Arial, Helvetica, sans-serif;margin: 20px;&quot;&gt;
        ///    &lt;div&gt;Estimado usuario de CONSULTREE&lt;/div&gt;
        ///    &lt;div style=&quot;padding-top: 10px;&quot;&gt;Se adjunta el informe de la evaluación DTI para :&lt;/div&gt;
        ///    &lt;div style=&quot;padding-top: 30px;&quot;&gt;        
        ///        Nomb [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CuerpoCorreo {
            get {
                return ResourceManager.GetString("CuerpoCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar.
        /// </summary>
        public static string Descargar {
            get {
                return ResourceManager.GetString("Descargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string EstadoActivo {
            get {
                return ResourceManager.GetString("EstadoActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivo.
        /// </summary>
        public static string EstadoInactivo {
            get {
                return ResourceManager.GetString("EstadoInactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string IdiomaEspanol {
            get {
                return ResourceManager.GetString("IdiomaEspanol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingles.
        /// </summary>
        public static string IdiomaIngles {
            get {
                return ResourceManager.GetString("IdiomaIngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portugues.
        /// </summary>
        public static string IdiomaPortugues {
            get {
                return ResourceManager.GetString("IdiomaPortugues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json.
        /// </summary>
        public static string LenguajeDatatables {
            get {
                return ResourceManager.GetString("LenguajeDatatables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es-ES.
        /// </summary>
        public static string LenguajeSelect {
            get {
                return ResourceManager.GetString("LenguajeSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Scripts/select2/i18n/es.js.
        /// </summary>
        public static string LenguajeSelectScript {
            get {
                return ResourceManager.GetString("LenguajeSelectScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Vamos a Completarlo!.
        /// </summary>
        public static string LoginBoton {
            get {
                return ResourceManager.GetString("LoginBoton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La sesión ha sido cerrada.
        /// </summary>
        public static string LoginCerrarSesion {
            get {
                return ResourceManager.GetString("LoginCerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string LoginClave {
            get {
                return ResourceManager.GetString("LoginClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ya esta en el sistema, desea cerrar la sesión existente?.
        /// </summary>
        public static string LoginDobleUsuario {
            get {
                return ResourceManager.GetString("LoginDobleUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña Erronea..
        /// </summary>
        public static string LoginError4 {
            get {
                return ResourceManager.GetString("LoginError4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIEMPO DE TRANSFORMACIÓN.
        /// </summary>
        public static string LoginEslogan {
            get {
                return ResourceManager.GetString("LoginEslogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿ESTÁ SU EMPRESA LISTA PARA UNA TRANSFORMACIÓN DIGITAL?.
        /// </summary>
        public static string LoginEslogan2 {
            get {
                return ResourceManager.GetString("LoginEslogan2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información.
        /// </summary>
        public static string LoginInfo {
            get {
                return ResourceManager.GetString("LoginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar sesión.
        /// </summary>
        public static string LoginSalirUsuario {
            get {
                return ResourceManager.GetString("LoginSalirUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña no puede ir en blanco..
        /// </summary>
        public static string LoginSinClave {
            get {
                return ResourceManager.GetString("LoginSinClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no existe..
        /// </summary>
        public static string LoginSinUsuario {
            get {
                return ResourceManager.GetString("LoginSinUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        public static string LoginUsuario {
            get {
                return ResourceManager.GetString("LoginUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idiomas del sistema.
        /// </summary>
        public static string MsgIdiomaBase {
            get {
                return ResourceManager.GetString("MsgIdiomaBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Encuesta.
        /// </summary>
        public static string Nombre_Encuesta {
            get {
                return ResourceManager.GetString("Nombre_Encuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombres.
        /// </summary>
        public static string Nombres {
            get {
                return ResourceManager.GetString("Nombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string Pais {
            get {
                return ResourceManager.GetString("Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se está procesando el contenido de la encuesta.
        /// </summary>
        public static string ProgresBar {
            get {
                return ResourceManager.GetString("ProgresBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Reporte.
        /// </summary>
        public static string Reporte {
            get {
                return ResourceManager.GetString("Reporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responder.
        /// </summary>
        public static string Responder {
            get {
                return ResourceManager.GetString("Responder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado.
        /// </summary>
        public static string Resultado {
            get {
                return ResourceManager.GetString("Resultado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador.
        /// </summary>
        public static string RolAdministrador {
            get {
                return ResourceManager.GetString("RolAdministrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliado.
        /// </summary>
        public static string RolAliado {
            get {
                return ResourceManager.GetString("RolAliado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string RolCliente {
            get {
                return ResourceManager.GetString("RolCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encuestado.
        /// </summary>
        public static string RolEncuestado {
            get {
                return ResourceManager.GetString("RolEncuestado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione....
        /// </summary>
        public static string Seleccione {
            get {
                return ResourceManager.GetString("Seleccione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione Idioma.
        /// </summary>
        public static string SeleccioneIdioma {
            get {
                return ResourceManager.GetString("SeleccioneIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguiente.
        /// </summary>
        public static string Siguiente {
            get {
                return ResourceManager.GetString("Siguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin responder.
        /// </summary>
        public static string Sin_responder {
            get {
                return ResourceManager.GetString("Sin_responder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indice de Transformación Digital.
        /// </summary>
        public static string SujetoCorreo {
            get {
                return ResourceManager.GetString("SujetoCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablero.
        /// </summary>
        public static string Tablero {
            get {
                return ResourceManager.GetString("Tablero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string Td_datetime {
            get {
                return ResourceManager.GetString("Td_datetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        public static string Td_email {
            get {
                return ResourceManager.GetString("Td_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero.
        /// </summary>
        public static string Td_number {
            get {
                return ResourceManager.GetString("Td_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rango.
        /// </summary>
        public static string Td_range {
            get {
                return ResourceManager.GetString("Td_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        public static string Td_tel {
            get {
                return ResourceManager.GetString("Td_tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto.
        /// </summary>
        public static string Td_text {
            get {
                return ResourceManager.GetString("Td_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # de Empleados.
        /// </summary>
        public static string UpdateU_CEmple {
            get {
                return ResourceManager.GetString("UpdateU_CEmple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo Trabajo.
        /// </summary>
        public static string UpdateU_CorreoT {
            get {
                return ResourceManager.GetString("UpdateU_CorreoT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Correo Trabajo.
        /// </summary>
        public static string UpdateU_CorreoTC {
            get {
                return ResourceManager.GetString("UpdateU_CorreoTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección Oficina.
        /// </summary>
        public static string UpdateU_DirT {
            get {
                return ResourceManager.GetString("UpdateU_DirT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        public static string UpdateU_Empresa {
            get {
                return ResourceManager.GetString("UpdateU_Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industria.
        /// </summary>
        public static string UpdateU_Industria {
            get {
                return ResourceManager.GetString("UpdateU_Industria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia.
        /// </summary>
        public static string UpdateU_Provincia {
            get {
                return ResourceManager.GetString("UpdateU_Provincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subsidiario.
        /// </summary>
        public static string UpdateU_Subsi {
            get {
                return ResourceManager.GetString("UpdateU_Subsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        public static string UpdateU_Telefono {
            get {
                return ResourceManager.GetString("UpdateU_Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título / Posición.
        /// </summary>
        public static string UpdateU_Titulo {
            get {
                return ResourceManager.GetString("UpdateU_Titulo", resourceCulture);
            }
        }
    }
}
